controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_position_controller:
      type: position_controllers/JointGroupPositionController

simple_position_controller:
  ros__parameters:
    joints:
      - c1_j
      - f1_j
      - t1_j
      - c2_j
      - f2_j
      - t2_j
      - c3_j
      - f3_j
      - t3_j
      - c4_j
      - f4_j
      - t4_j
      - c5_j
      - f5_j
      - t5_j
      - c6_j
      - f6_j
      - t6_j