joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: std_msgs/msg/Float64MultiArray
      topic_name: hexapod_controller/joy_commands
      deadman_buttons: [5]
      axis_mappings:
        data[0]:
          axis: 1
          scale: 1.0
          offset: 0.0
        data[1]:
          axis: 3
          scale: 8.0
          offset: 0.0
#complete when controller arrives
